var THREE=THREE||{};window.Int32Array||(window.Int32Array=Array,window.Float32Array=Array);THREE.Color=function(a){this.setHex(a)};
THREE.Color.prototype={copy:function(a){this.r=a.r;this.g=a.g;this.b=a.b;this.hex=a.hex},setHex:function(a){this.hex=~~a&16777215;this.updateRGB()},setRGB:function(a,b,c){this.r=a;this.g=b;this.b=c;this.updateHex()},setHSV:function(a,b,c){var d,e,g,f,h,i;if(c==0)d=e=g=0;else{f=Math.floor(a*6);h=a*6-f;a=c*(1-b);i=c*(1-b*h);b=c*(1-b*(1-h));switch(f){case 1:d=i;e=c;g=a;break;case 2:d=a;e=c;g=b;break;case 3:d=a;e=i;g=c;break;case 4:d=b;e=a;g=c;break;case 5:d=c;e=a;g=i;break;case 6:case 0:d=c;e=b;g=a}}this.setRGB(d,
e,g)},updateHex:function(){this.hex=~~(this.r*255)<<16^~~(this.g*255)<<8^~~(this.b*255)},updateRGB:function(){this.r=(this.hex>>16&255)/255;this.g=(this.hex>>8&255)/255;this.b=(this.hex&255)/255},clone:function(){return new THREE.Color(this.hex)}};THREE.Vector2=function(a,b){this.set(a||0,b||0)};
THREE.Vector2.prototype={set:function(a,b){this.x=a;this.y=b;return this},copy:function(a){this.x=a.x;this.y=a.y;return this},clone:function(){return new THREE.Vector2(this.x,this.y)},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;return this},addSelf:function(a){this.x=this.x+a.x;this.y=this.y+a.y;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-b.y;return this},subSelf:function(a){this.x=this.x-a.x;this.y=this.y-a.y;return this},multiplyScalar:function(a){this.x=this.x*a;this.y=this.y*
a;return this},divideScalar:function(a){if(a){this.x=this.x/a;this.y=this.y/a}else this.set(0,0);return this},negate:function(){return this.multiplyScalar(-1)},dot:function(a){return this.x*a.x+this.y*a.y},lengthSq:function(){return this.x*this.x+this.y*this.y},length:function(){return Math.sqrt(this.lengthSq())},normalize:function(){return this.divideScalar(this.length())},setLength:function(a){return this.normalize().multiplyScalar(a)},unit:function(){return this.normalize()}};
THREE.Vector3=function(a,b,c){this.set(a||0,b||0,c||0)};
THREE.Vector3.prototype={set:function(a,b,c){this.x=a;this.y=b;this.z=c;return this},copy:function(a){this.x=a.x;this.y=a.y;this.z=a.z;return this},clone:function(){return new THREE.Vector3(this.x,this.y,this.z)},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;this.z=a.z+b.z;return this},addSelf:function(a){this.x=this.x+a.x;this.y=this.y+a.y;this.z=this.z+a.z;return this},addScalar:function(a){this.x=this.x+a;this.y=this.y+a;this.z=this.z+a;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-
b.y;this.z=a.z-b.z;return this},subSelf:function(a){this.x=this.x-a.x;this.y=this.y-a.y;this.z=this.z-a.z;return this},multiply:function(a,b){this.x=a.x*b.x;this.y=a.y*b.y;this.z=a.z*b.z;return this},multiplySelf:function(a){this.x=this.x*a.x;this.y=this.y*a.y;this.z=this.z*a.y;return this},multiplyScalar:function(a){this.x=this.x*a;this.y=this.y*a;this.z=this.z*a;return this},divideSelf:function(a){return this.divide(this,a)},divideScalar:function(a){if(a){this.x=this.x/a;this.y=this.y/a;this.z=
this.z/a}else this.set(0,0,0);return this},negate:function(){return this.multiplyScalar(-1)},dot:function(a){return this.x*a.x+this.y*a.y+this.z*a.z},lengthSq:function(){return this.x*this.x+this.y*this.y+this.z*this.z},length:function(){return Math.sqrt(this.lengthSq())},lengthManhattan:function(){return this.x+this.y+this.z},normalize:function(){return this.divideScalar(this.length())},setLength:function(a){return this.normalize().multiplyScalar(a)},cross:function(a,b){this.x=a.y*b.z-a.z*b.y;this.y=
a.z*b.x-a.x*b.z;this.z=a.x*b.y-a.y*b.x;return this},crossSelf:function(a){return this.set(this.y*a.z-this.z*a.y,this.z*a.x-this.x*a.z,this.x*a.y-this.y*a.x)},distanceTo:function(a){return Math.sqrt(this.distanceToSquared(a))},distanceToSquared:function(a){return(new THREE.Vector3).sub(this,a).lengthSq()},setPositionFromMatrix:function(a){this.x=a.n14;this.y=a.n24;this.z=a.n34},setRotationFromMatrix:function(a){var b=Math.cos(this.y);this.y=Math.asin(a.n13);if(Math.abs(b)>1.0E-5){this.x=Math.atan2(-a.n23/
b,a.n33/b);this.z=Math.atan2(-a.n12/b,a.n11/b)}else{this.x=0;this.z=Math.atan2(a.n21,a.n22)}},isZero:function(){return this.lengthSq()<1.0E-4}};THREE.Vector4=function(a,b,c,d){this.set(a||0,b||0,c||0,d||1)};
THREE.Vector4.prototype={set:function(a,b,c,d){this.x=a;this.y=b;this.z=c;this.w=d;return this},copy:function(a){return this.set(a.x,a.y,a.z,a.w||1)},clone:function(){return new THREE.Vector4(this.x,this.y,this.z,this.w)},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;this.z=a.z+b.z;this.w=a.w+b.w;return this},addSelf:function(a){this.x=this.x+a.x;this.y=this.y+a.y;this.z=this.z+a.z;this.w=this.w+a.w;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-b.y;this.z=a.z-b.z;this.w=a.w-b.w;return this},
subSelf:function(a){this.x=this.x-a.x;this.y=this.y-a.y;this.z=this.z-a.z;this.w=this.w-a.w;return this},multiplyScalar:function(a){this.x=this.x*a;this.y=this.y*a;this.z=this.z*a;this.w=this.w*a;return this},divideScalar:function(a){if(a){this.x=this.x/a;this.y=this.y/a;this.z=this.z/a;this.w=this.w/a}else this.set(0,0,0,1);return this},negate:function(){return this.multiplyScalar(-1)},dot:function(a){return this.x*a.x+this.y*a.y+this.z*a.z+this.w*a.w},lengthSq:function(){return this.dot(this)},
length:function(){return Math.sqrt(this.lengthSq())},normalize:function(){return this.divideScalar(this.length())},setLength:function(a){return this.normalize().multiplyScalar(a)},lerpSelf:function(a,b){this.x=this.x+(a.x-this.x)*b;this.y=this.y+(a.y-this.y)*b;this.z=this.z+(a.z-this.z)*b;this.w=this.w+(a.w-this.w)*b;return this}};THREE.Ray=function(a,b){this.origin=a||new THREE.Vector3;this.direction=b||new THREE.Vector3};
THREE.Ray.prototype={intersectScene:function(a){return this.intersectObjects(a.objects)},intersectObjects:function(a){var b,c,d=[];b=0;for(c=a.length;b<c;b++)d=d.concat(this.intersectObject(a[b]));d.sort(function(a,b){return a.distance-b.distance});return d},intersectObject:function(a){function b(a,b,c){var d;d=c.position.clone().subSelf(a).dot(b);if(d<0)return false;a=a.clone().addSelf(b.clone().multiplyScalar(d));return c.position.distanceTo(a)}function c(a,b,c,d){var d=d.clone().subSelf(b),c=c.clone().subSelf(b),
e=a.clone().subSelf(b),a=d.dot(d),b=d.dot(c),d=d.dot(e),f=c.dot(c),c=c.dot(e),e=1/(a*f-b*b),f=(f*d-b*c)*e,a=(a*c-b*d)*e;return f>0&&a>0&&f+a<1}if(a instanceof THREE.Particle){var d=b(this.origin,this.direction,a);return!d||d>a.scale.x?[]:[{distance:d,point:a.position,face:null,object:a}]}if(a instanceof THREE.Mesh){d=b(this.origin,this.direction,a);if(!d||d>a.geometry.boundingSphere.radius*Math.max(a.scale.x,Math.max(a.scale.y,a.scale.z)))return[];var e,g,f,h,i,j,m,n,l,o,k=a.geometry,s=k.vertices,
t=[],d=0;for(e=k.faces.length;d<e;d++){g=k.faces[d];l=this.origin.clone();o=this.direction.clone();j=a.matrixWorld;f=j.multiplyVector3(s[g.a].position.clone());h=j.multiplyVector3(s[g.b].position.clone());i=j.multiplyVector3(s[g.c].position.clone());j=g instanceof THREE.Face4?j.multiplyVector3(s[g.d].position.clone()):null;m=a.matrixRotationWorld.multiplyVector3(g.normal.clone());n=o.dot(m);if(a.doubleSided||(a.flipSided?n>0:n<0)){m=m.dot((new THREE.Vector3).sub(f,l))/n;l=l.addSelf(o.multiplyScalar(m));
if(g instanceof THREE.Face3){if(c(l,f,h,i)){g={distance:this.origin.distanceTo(l),point:l,face:g,object:a};t.push(g)}}else if(g instanceof THREE.Face4&&(c(l,f,h,j)||c(l,h,i,j))){g={distance:this.origin.distanceTo(l),point:l,face:g,object:a};t.push(g)}}}return t}return[]}};
THREE.Rectangle=function(){function a(){g=d-b;f=e-c}var b,c,d,e,g,f,h=true;this.getX=function(){return b};this.getY=function(){return c};this.getWidth=function(){return g};this.getHeight=function(){return f};this.getLeft=function(){return b};this.getTop=function(){return c};this.getRight=function(){return d};this.getBottom=function(){return e};this.set=function(f,g,m,n){h=false;b=f;c=g;d=m;e=n;a()};this.addPoint=function(f,g){if(h){h=false;b=f;c=g;d=f;e=g}else{b=b<f?b:f;c=c<g?c:g;d=d>f?d:f;e=e>g?
e:g}a()};this.add3Points=function(f,g,m,n,l,o){if(h){h=false;b=f<m?f<l?f:l:m<l?m:l;c=g<n?g<o?g:o:n<o?n:o;d=f>m?f>l?f:l:m>l?m:l;e=g>n?g>o?g:o:n>o?n:o}else{b=f<m?f<l?f<b?f:b:l<b?l:b:m<l?m<b?m:b:l<b?l:b;c=g<n?g<o?g<c?g:c:o<c?o:c:n<o?n<c?n:c:o<c?o:c;d=f>m?f>l?f>d?f:d:l>d?l:d:m>l?m>d?m:d:l>d?l:d;e=g>n?g>o?g>e?g:e:o>e?o:e:n>o?n>e?n:e:o>e?o:e}a()};this.addRectangle=function(f){if(h){h=false;b=f.getLeft();c=f.getTop();d=f.getRight();e=f.getBottom()}else{b=b<f.getLeft()?b:f.getLeft();c=c<f.getTop()?c:f.getTop();
d=d>f.getRight()?d:f.getRight();e=e>f.getBottom()?e:f.getBottom()}a()};this.inflate=function(f){b=b-f;c=c-f;d=d+f;e=e+f;a()};this.minSelf=function(f){b=b>f.getLeft()?b:f.getLeft();c=c>f.getTop()?c:f.getTop();d=d<f.getRight()?d:f.getRight();e=e<f.getBottom()?e:f.getBottom();a()};this.instersects=function(a){return Math.min(d,a.getRight())-Math.max(b,a.getLeft())>=0&&Math.min(e,a.getBottom())-Math.max(c,a.getTop())>=0};this.empty=function(){h=true;e=d=c=b=0;a()};this.isEmpty=function(){return h}};
THREE.Matrix3=function(){this.m=[]};THREE.Matrix3.prototype={transpose:function(){var a,b=this.m;a=b[1];b[1]=b[3];b[3]=a;a=b[2];b[2]=b[6];b[6]=a;a=b[5];b[5]=b[7];b[7]=a;return this},transposeIntoArray:function(a){var b=this.m;a[0]=b[0];a[1]=b[3];a[2]=b[6];a[3]=b[1];a[4]=b[4];a[5]=b[7];a[6]=b[2];a[7]=b[5];a[8]=b[8];return this}};
THREE.Matrix4=function(a,b,c,d,e,g,f,h,i,j,m,n,l,o,k,s){this.set(a||1,b||0,c||0,d||0,e||0,g||1,f||0,h||0,i||0,j||0,m||1,n||0,l||0,o||0,k||0,s||1);this.flat=Array(16);this.m33=new THREE.Matrix3};
THREE.Matrix4.prototype={set:function(a,b,c,d,e,g,f,h,i,j,m,n,l,o,k,s){this.n11=a;this.n12=b;this.n13=c;this.n14=d;this.n21=e;this.n22=g;this.n23=f;this.n24=h;this.n31=i;this.n32=j;this.n33=m;this.n34=n;this.n41=l;this.n42=o;this.n43=k;this.n44=s;return this},identity:function(){this.set(1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1);return this},copy:function(a){this.set(a.n11,a.n12,a.n13,a.n14,a.n21,a.n22,a.n23,a.n24,a.n31,a.n32,a.n33,a.n34,a.n41,a.n42,a.n43,a.n44);return this},lookAt:function(a,b,c){var d=THREE.Matrix4.__v1,
e=THREE.Matrix4.__v2,g=THREE.Matrix4.__v3;g.sub(a,b).normalize();if(g.length()===0)g.z=1;d.cross(c,g).normalize();if(d.length()===0){g.x=g.x+1.0E-4;d.cross(c,g).normalize()}e.cross(g,d).normalize();this.n11=d.x;this.n12=e.x;this.n13=g.x;this.n21=d.y;this.n22=e.y;this.n23=g.y;this.n31=d.z;this.n32=e.z;this.n33=g.z;return this},multiplyVector3:function(a){var b=a.x,c=a.y,d=a.z,e=1/(this.n41*b+this.n42*c+this.n43*d+this.n44);a.x=(this.n11*b+this.n12*c+this.n13*d+this.n14)*e;a.y=(this.n21*b+this.n22*
c+this.n23*d+this.n24)*e;a.z=(this.n31*b+this.n32*c+this.n33*d+this.n34)*e;return a},multiplyVector4:function(a){var b=a.x,c=a.y,d=a.z,e=a.w;a.x=this.n11*b+this.n12*c+this.n13*d+this.n14*e;a.y=this.n21*b+this.n22*c+this.n23*d+this.n24*e;a.z=this.n31*b+this.n32*c+this.n33*d+this.n34*e;a.w=this.n41*b+this.n42*c+this.n43*d+this.n44*e;return a},rotateAxis:function(a){var b=a.x,c=a.y,d=a.z;a.x=b*this.n11+c*this.n12+d*this.n13;a.y=b*this.n21+c*this.n22+d*this.n23;a.z=b*this.n31+c*this.n32+d*this.n33;a.normalize();
return a},crossVector:function(a){var b=new THREE.Vector4;b.x=this.n11*a.x+this.n12*a.y+this.n13*a.z+this.n14*a.w;b.y=this.n21*a.x+this.n22*a.y+this.n23*a.z+this.n24*a.w;b.z=this.n31*a.x+this.n32*a.y+this.n33*a.z+this.n34*a.w;b.w=a.w?this.n41*a.x+this.n42*a.y+this.n43*a.z+this.n44*a.w:1;return b},multiply:function(a,b){var c=a.n11,d=a.n12,e=a.n13,g=a.n14,f=a.n21,h=a.n22,i=a.n23,j=a.n24,m=a.n31,n=a.n32,l=a.n33,o=a.n34,k=a.n41,s=a.n42,t=a.n43,v=a.n44,y=b.n11,B=b.n12,w=b.n13,z=b.n14,q=b.n21,E=b.n22,
r=b.n23,u=b.n24,p=b.n31,J=b.n32,S=b.n33,N=b.n34;this.n11=c*y+d*q+e*p;this.n12=c*B+d*E+e*J;this.n13=c*w+d*r+e*S;this.n14=c*z+d*u+e*N+g;this.n21=f*y+h*q+i*p;this.n22=f*B+h*E+i*J;this.n23=f*w+h*r+i*S;this.n24=f*z+h*u+i*N+j;this.n31=m*y+n*q+l*p;this.n32=m*B+n*E+l*J;this.n33=m*w+n*r+l*S;this.n34=m*z+n*u+l*N+o;this.n41=k*y+s*q+t*p;this.n42=k*B+s*E+t*J;this.n43=k*w+s*r+t*S;this.n44=k*z+s*u+t*N+v;return this},multiplyToArray:function(a,b,c){this.multiply(a,b);c[0]=this.n11;c[1]=this.n21;c[2]=this.n31;c[3]=
this.n41;c[4]=this.n12;c[5]=this.n22;c[6]=this.n32;c[7]=this.n42;c[8]=this.n13;c[9]=this.n23;c[10]=this.n33;c[11]=this.n43;c[12]=this.n14;c[13]=this.n24;c[14]=this.n34;c[15]=this.n44;return this},multiplySelf:function(a){this.multiply(this,a);return this},multiplyScalar:function(a){this.n11=this.n11*a;this.n12=this.n12*a;this.n13=this.n13*a;this.n14=this.n14*a;this.n21=this.n21*a;this.n22=this.n22*a;this.n23=this.n23*a;this.n24=this.n24*a;this.n31=this.n31*a;this.n32=this.n32*a;this.n33=this.n33*
a;this.n34=this.n34*a;this.n41=this.n41*a;this.n42=this.n42*a;this.n43=this.n43*a;this.n44=this.n44*a;return this},determinant:function(){var a=this.n11,b=this.n12,c=this.n13,d=this.n14,e=this.n21,g=this.n22,f=this.n23,h=this.n24,i=this.n31,j=this.n32,m=this.n33,n=this.n34,l=this.n41,o=this.n42,k=this.n43,s=this.n44;return d*f*j*l-c*h*j*l-d*g*m*l+b*h*m*l+c*g*n*l-b*f*n*l-d*f*i*o+c*h*i*o+d*e*m*o-a*h*m*o-c*e*n*o+a*f*n*o+d*g*i*k-b*h*i*k-d*e*j*k+a*h*j*k+b*e*n*k-a*g*n*k-c*g*i*s+b*f*i*s+c*e*j*s-a*f*j*s-
b*e*m*s+a*g*m*s},transpose:function(){var a;a=this.n21;this.n21=this.n12;this.n12=a;a=this.n31;this.n31=this.n13;this.n13=a;a=this.n32;this.n32=this.n23;this.n23=a;a=this.n41;this.n41=this.n14;this.n14=a;a=this.n42;this.n42=this.n24;this.n24=a;a=this.n43;this.n43=this.n34;this.n43=a;return this},clone:function(){var a=new THREE.Matrix4;a.n11=this.n11;a.n12=this.n12;a.n13=this.n13;a.n14=this.n14;a.n21=this.n21;a.n22=this.n22;a.n23=this.n23;a.n24=this.n24;a.n31=this.n31;a.n32=this.n32;a.n33=this.n33;
a.n34=this.n34;a.n41=this.n41;a.n42=this.n42;a.n43=this.n43;a.n44=this.n44;return a},flatten:function(){this.flat[0]=this.n11;this.flat[1]=this.n21;this.flat[2]=this.n31;this.flat[3]=this.n41;this.flat[4]=this.n12;this.flat[5]=this.n22;this.flat[6]=this.n32;this.flat[7]=this.n42;this.flat[8]=this.n13;this.flat[9]=this.n23;this.flat[10]=this.n33;this.flat[11]=this.n43;this.flat[12]=this.n14;this.flat[13]=this.n24;this.flat[14]=this.n34;this.flat[15]=this.n44;return this.flat},flattenToArray:function(a){a[0]=
this.n11;a[1]=this.n21;a[2]=this.n31;a[3]=this.n41;a[4]=this.n12;a[5]=this.n22;a[6]=this.n32;a[7]=this.n42;a[8]=this.n13;a[9]=this.n23;a[10]=this.n33;a[11]=this.n43;a[12]=this.n14;a[13]=this.n24;a[14]=this.n34;a[15]=this.n44;return a},flattenToArrayOffset:function(a,b){a[b]=this.n11;a[b+1]=this.n21;a[b+2]=this.n31;a[b+3]=this.n41;a[b+4]=this.n12;a[b+5]=this.n22;a[b+6]=this.n32;a[b+7]=this.n42;a[b+8]=this.n13;a[b+9]=this.n23;a[b+10]=this.n33;a[b+11]=this.n43;a[b+12]=this.n14;a[b+13]=this.n24;a[b+14]=
this.n34;a[b+15]=this.n44;return a},setTranslation:function(a,b,c){this.set(1,0,0,a,0,1,0,b,0,0,1,c,0,0,0,1);return this},setScale:function(a,b,c){this.set(a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1);return this},setRotationX:function(a){var b=Math.cos(a),a=Math.sin(a);this.set(1,0,0,0,0,b,-a,0,0,a,b,0,0,0,0,1);return this},setRotationY:function(a){var b=Math.cos(a),a=Math.sin(a);this.set(b,0,a,0,0,1,0,0,-a,0,b,0,0,0,0,1);return this},setRotationZ:function(a){var b=Math.cos(a),a=Math.sin(a);this.set(b,-a,0,
0,a,b,0,0,0,0,1,0,0,0,0,1);return this},setRotationAxis:function(a,b){var c=Math.cos(b),d=Math.sin(b),e=1-c,g=a.x,f=a.y,h=a.z,i=e*g,j=e*f;this.set(i*g+c,i*f-d*h,i*h+d*f,0,i*f+d*h,j*f+c,j*h-d*g,0,i*h-d*f,j*h+d*g,e*h*h+c,0,0,0,0,1);return this},setPosition:function(a){this.n14=a.x;this.n24=a.y;this.n34=a.z;return this},getPosition:function(){if(!this.position)this.position=new THREE.Vector3;this.position.set(this.n14,this.n24,this.n34);return this.position},getColumnX:function(){if(!this.columnX)this.columnX=
new THREE.Vector3;this.columnX.set(this.n11,this.n21,this.n31);return this.columnX},getColumnY:function(){if(!this.columnY)this.columnY=new THREE.Vector3;this.columnY.set(this.n12,this.n22,this.n32);return this.columnY},getColumnZ:function(){if(!this.columnZ)this.columnZ=new THREE.Vector3;this.columnZ.set(this.n13,this.n23,this.n33);return this.columnZ},setRotationFromEuler:function(a){var b=a.x,c=a.y,d=a.z,a=Math.cos(b),b=Math.sin(b),e=Math.cos(c),c=Math.sin(c),g=Math.cos(d),d=Math.sin(d),f=a*c,
h=b*c;this.n11=e*g;this.n12=-e*d;this.n13=c;this.n21=h*g+a*d;this.n22=-h*d+a*g;this.n23=-b*e;this.n31=-f*g+b*d;this.n32=f*d+b*g;this.n33=a*e;return this},setRotationFromQuaternion:function(a){var b=a.x,c=a.y,d=a.z,e=a.w,g=b+b,f=c+c,h=d+d,a=b*g,i=b*f,b=b*h,j=c*f,c=c*h,d=d*h,g=e*g,f=e*f,e=e*h;this.n11=1-(j+d);this.n12=i-e;this.n13=b+f;this.n21=i+e;this.n22=1-(a+d);this.n23=c-g;this.n31=b-f;this.n32=c+g;this.n33=1-(a+j);return this},scale:function(a){var b=a.x,c=a.y,a=a.z;this.n11=this.n11*b;this.n12=
this.n12*c;this.n13=this.n13*a;this.n21=this.n21*b;this.n22=this.n22*c;this.n23=this.n23*a;this.n31=this.n31*b;this.n32=this.n32*c;this.n33=this.n33*a;this.n41=this.n41*b;this.n42=this.n42*c;this.n43=this.n43*a;return this},extractPosition:function(a){this.n14=a.n14;this.n24=a.n24;this.n34=a.n34},extractRotation:function(a,b){var c=1/b.x,d=1/b.y,e=1/b.z;this.n11=a.n11*c;this.n21=a.n21*c;this.n31=a.n31*c;this.n12=a.n12*d;this.n22=a.n22*d;this.n32=a.n32*d;this.n13=a.n13*e;this.n23=a.n23*e;this.n33=
a.n33*e}};
THREE.Matrix4.makeInvert=function(a,b){var c=a.n11,d=a.n12,e=a.n13,g=a.n14,f=a.n21,h=a.n22,i=a.n23,j=a.n24,m=a.n31,n=a.n32,l=a.n33,o=a.n34,k=a.n41,s=a.n42,t=a.n43,v=a.n44;b===void 0&&(b=new THREE.Matrix4);b.n11=i*o*s-j*l*s+j*n*t-h*o*t-i*n*v+h*l*v;b.n12=g*l*s-e*o*s-g*n*t+d*o*t+e*n*v-d*l*v;b.n13=e*j*s-g*i*s+g*h*t-d*j*t-e*h*v+d*i*v;b.n14=g*i*n-e*j*n-g*h*l+d*j*l+e*h*o-d*i*o;b.n21=j*l*k-i*o*k-j*m*t+f*o*t+i*m*v-f*l*v;b.n22=e*o*k-g*l*k+g*m*t-c*o*t-e*m*v+c*l*v;b.n23=g*i*k-e*j*k-g*f*t+c*j*t+e*f*v-c*i*v;b.n24=
e*j*m-g*i*m+g*f*l-c*j*l-e*f*o+c*i*o;b.n31=h*o*k-j*n*k+j*m*s-f*o*s-h*m*v+f*n*v;b.n32=g*n*k-d*o*k-g*m*s+c*o*s+d*m*v-c*n*v;b.n33=e*j*k-g*h*k+g*f*s-c*j*s-d*f*v+c*h*v;b.n34=g*h*m-d*j*m-g*f*n+c*j*n+d*f*o-c*h*o;b.n41=i*n*k-h*l*k-i*m*s+f*l*s+h*m*t-f*n*t;b.n42=d*l*k-e*n*k+e*m*s-c*l*s-d*m*t+c*n*t;b.n43=e*h*k-d*i*k-e*f*s+c*i*s+d*f*t-c*h*t;b.n44=d*i*m-e*h*m+e*f*n-c*i*n-d*f*l+c*h*l;b.multiplyScalar(1/a.determinant());return b};
THREE.Matrix4.makeInvert3x3=function(a){var b=a.m33,c=b.m,d=a.n33*a.n22-a.n32*a.n23,e=-a.n33*a.n21+a.n31*a.n23,g=a.n32*a.n21-a.n31*a.n22,f=-a.n33*a.n12+a.n32*a.n13,h=a.n33*a.n11-a.n31*a.n13,i=-a.n32*a.n11+a.n31*a.n12,j=a.n23*a.n12-a.n22*a.n13,m=-a.n23*a.n11+a.n21*a.n13,n=a.n22*a.n11-a.n21*a.n12,a=a.n11*d+a.n21*f+a.n31*j;a==0&&console.error("THREE.Matrix4.makeInvert3x3: Matrix not invertible.");a=1/a;c[0]=a*d;c[1]=a*e;c[2]=a*g;c[3]=a*f;c[4]=a*h;c[5]=a*i;c[6]=a*j;c[7]=a*m;c[8]=a*n;return b};
THREE.Matrix4.makeFrustum=function(a,b,c,d,e,g){var f;f=new THREE.Matrix4;f.n11=2*e/(b-a);f.n12=0;f.n13=(b+a)/(b-a);f.n14=0;f.n21=0;f.n22=2*e/(d-c);f.n23=(d+c)/(d-c);f.n24=0;f.n31=0;f.n32=0;f.n33=-(g+e)/(g-e);f.n34=-2*g*e/(g-e);f.n41=0;f.n42=0;f.n43=-1;f.n44=0;return f};THREE.Matrix4.makePerspective=function(a,b,c,d){var e,a=c*Math.tan(a*Math.PI/360);e=-a;return THREE.Matrix4.makeFrustum(e*b,a*b,e,a,c,d)};
THREE.Matrix4.makeOrtho=function(a,b,c,d,e,g){var f,h,i,j;f=new THREE.Matrix4;h=b-a;i=c-d;j=g-e;f.n11=2/h;f.n12=0;f.n13=0;f.n14=-((b+a)/h);f.n21=0;f.n22=2/i;f.n23=0;f.n24=-((c+d)/i);f.n31=0;f.n32=0;f.n33=-2/j;f.n34=-((g+e)/j);f.n41=0;f.n42=0;f.n43=0;f.n44=1;return f};THREE.Matrix4.__v1=new THREE.Vector3;THREE.Matrix4.__v2=new THREE.Vector3;THREE.Matrix4.__v3=new THREE.Vector3;
THREE.Object3D=function(){this.parent=void 0;this.children=[];this.up=new THREE.Vector3(0,1,0);this.position=new THREE.Vector3;this.rotation=new THREE.Vector3;this.scale=new THREE.Vector3(1,1,1);this.dynamic=false;this.rotationAutoUpdate=true;this.matrix=new THREE.Matrix4;this.matrixWorld=new THREE.Matrix4;this.matrixRotationWorld=new THREE.Matrix4;this.matrixWorldNeedsUpdate=this.matrixAutoUpdate=true;this.quaternion=new THREE.Quaternion;this.useQuaternion=false;this.boundRadius=0;this.boundRadiusScale=
1;this.visible=true;this._vector=new THREE.Vector3;this.name=""};
THREE.Object3D.prototype={translate:function(a,b){this.matrix.rotateAxis(b);this.position.addSelf(b.multiplyScalar(a))},translateX:function(a){this.translate(a,this._vector.set(1,0,0))},translateY:function(a){this.translate(a,this._vector.set(0,1,0))},translateZ:function(a){this.translate(a,this._vector.set(0,0,1))},lookAt:function(a){this.matrix.lookAt(a,this.position,this.up);this.rotationAutoUpdate&&this.rotation.setRotationFromMatrix(this.matrix)},addChild:function(a){if(this.children.indexOf(a)===
-1){a.parent!==void 0&&a.parent.removeChild(a);a.parent=this;this.children.push(a);for(var b=this;b.parent!==void 0;)b=b.parent;b!==void 0&&b instanceof THREE.Scene&&b.addChildRecurse(a)}},removeChild:function(a){var b=this.children.indexOf(a);if(b!==-1){a.parent=void 0;this.children.splice(b,1)}},getChildByName:function(a,b){var c,d,e;c=0;for(d=this.children.length;c<d;c++){e=this.children[c];if(e.name===a)return e;if(b){e=e.getChildByName(a,b);if(e!==void 0)return e}}},updateMatrix:function(){this.matrix.setPosition(this.position);
this.useQuaternion?this.matrix.setRotationFromQuaternion(this.quaternion):this.matrix.setRotationFromEuler(this.rotation);if(this.scale.x!==1||this.scale.y!==1||this.scale.z!==1){this.matrix.scale(this.scale);this.boundRadiusScale=Math.max(this.scale.x,Math.max(this.scale.y,this.scale.z))}this.matrixWorldNeedsUpdate=true},update:function(a,b,c){this.matrixAutoUpdate&&this.updateMatrix();if(this.matrixWorldNeedsUpdate||b){a?this.matrixWorld.multiply(a,this.matrix):this.matrixWorld.copy(this.matrix);
this.matrixRotationWorld.extractRotation(this.matrixWorld,this.scale);this.matrixWorldNeedsUpdate=false;b=true}for(var a=0,d=this.children.length;a<d;a++)this.children[a].update(this.matrixWorld,b,c)}};THREE.Quaternion=function(a,b,c,d){this.set(a||0,b||0,c||0,d!==void 0?d:1)};
THREE.Quaternion.prototype={set:function(a,b,c,d){this.x=a;this.y=b;this.z=c;this.w=d;return this},copy:function(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=a.w;return this},setFromEuler:function(a){var b=0.5*Math.PI/360,c=a.x*b,d=a.y*b,e=a.z*b,a=Math.cos(d),d=Math.sin(d),b=Math.cos(-e),e=Math.sin(-e),g=Math.cos(c),c=Math.sin(c),f=a*b,h=d*e;this.w=f*g-h*c;this.x=f*c+h*g;this.y=d*b*g+a*e*c;this.z=a*e*g-d*b*c;return this},setFromAxisAngle:function(a,b){var c=b/2,d=Math.sin(c);this.x=a.x*d;this.y=a.y*
d;this.z=a.z*d;this.w=Math.cos(c);return this},calculateW:function(){this.w=-Math.sqrt(Math.abs(1-this.x*this.x-this.y*this.y-this.z*this.z));return this},inverse:function(){this.x=this.x*-1;this.y=this.y*-1;this.z=this.z*-1;return this},length:function(){return Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z+this.w*this.w)},normalize:function(){var a=Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z+this.w*this.w);if(a==0)this.w=this.z=this.y=this.x=0;else{a=1/a;this.x=this.x*a;this.y=this.y*
a;this.z=this.z*a;this.w=this.w*a}return this},multiplySelf:function(a){var b=this.x,c=this.y,d=this.z,e=this.w,g=a.x,f=a.y,h=a.z,a=a.w;this.x=b*a+e*g+c*h-d*f;this.y=c*a+e*f+d*g-b*h;this.z=d*a+e*h+b*f-c*g;this.w=e*a-b*g-c*f-d*h;return this},multiply:function(a,b){this.x=a.x*b.w+a.y*b.z-a.z*b.y+a.w*b.x;this.y=-a.x*b.z+a.y*b.w+a.z*b.x+a.w*b.y;this.z=a.x*b.y-a.y*b.x+a.z*b.w+a.w*b.z;this.w=-a.x*b.x-a.y*b.y-a.z*b.z+a.w*b.w;return this},multiplyVector3:function(a,b){b||(b=a);var c=a.x,d=a.y,e=a.z,g=this.x,
f=this.y,h=this.z,i=this.w,j=i*c+f*e-h*d,m=i*d+h*c-g*e,n=i*e+g*d-f*c,c=-g*c-f*d-h*e;b.x=j*i+c*-g+m*-h-n*-f;b.y=m*i+c*-f+n*-g-j*-h;b.z=n*i+c*-h+j*-f-m*-g;return b}};
THREE.Quaternion.slerp=function(a,b,c,d){var e=a.w*b.w+a.x*b.x+a.y*b.y+a.z*b.z;if(Math.abs(e)>=1){c.w=a.w;c.x=a.x;c.y=a.y;c.z=a.z;return c}var g=Math.acos(e),f=Math.sqrt(1-e*e);if(Math.abs(f)<0.001){c.w=0.5*(a.w+b.w);c.x=0.5*(a.x+b.x);c.y=0.5*(a.y+b.y);c.z=0.5*(a.z+b.z);return c}e=Math.sin((1-d)*g)/f;d=Math.sin(d*g)/f;c.w=a.w*e+b.w*d;c.x=a.x*e+b.x*d;c.y=a.y*e+b.y*d;c.z=a.z*e+b.z*d;return c};THREE.Vertex=function(a){this.position=a||new THREE.Vector3};
THREE.Face3=function(a,b,c,d,e,g){this.a=a;this.b=b;this.c=c;this.normal=d instanceof THREE.Vector3?d:new THREE.Vector3;this.vertexNormals=d instanceof Array?d:[];this.color=e instanceof THREE.Color?e:new THREE.Color;this.vertexColors=e instanceof Array?e:[];this.vertexTangents=[];this.materials=g instanceof Array?g:[g];this.centroid=new THREE.Vector3};
THREE.Face4=function(a,b,c,d,e,g,f){this.a=a;this.b=b;this.c=c;this.d=d;this.normal=e instanceof THREE.Vector3?e:new THREE.Vector3;this.vertexNormals=e instanceof Array?e:[];this.color=g instanceof THREE.Color?g:new THREE.Color;this.vertexColors=g instanceof Array?g:[];this.vertexTangents=[];this.materials=f instanceof Array?f:[f];this.centroid=new THREE.Vector3};THREE.UV=function(a,b){this.set(a||0,b||0)};
THREE.UV.prototype={set:function(a,b){this.u=a;this.v=b;return this},copy:function(a){this.set(a.u,a.v);return this}};THREE.Geometry=function(){this.id="Geometry"+THREE.GeometryIdCounter++;this.vertices=[];this.colors=[];this.faces=[];this.edges=[];this.faceUvs=[[]];this.faceVertexUvs=[[]];this.morphTargets=[];this.morphColors=[];this.skinWeights=[];this.skinIndices=[];this.boundingSphere=this.boundingBox=null;this.hasTangents=false};
THREE.Geometry.prototype={computeCentroids:function(){var a,b,c;a=0;for(b=this.faces.length;a<b;a++){c=this.faces[a];c.centroid.set(0,0,0);if(c instanceof THREE.Face3){c.centroid.addSelf(this.vertices[c.a].position);c.centroid.addSelf(this.vertices[c.b].position);c.centroid.addSelf(this.vertices[c.c].position);c.centroid.divideScalar(3)}else if(c instanceof THREE.Face4){c.centroid.addSelf(this.vertices[c.a].position);c.centroid.addSelf(this.vertices[c.b].position);c.centroid.addSelf(this.vertices[c.c].position);
c.centroid.addSelf(this.vertices[c.d].position);c.centroid.divideScalar(4)}}},computeFaceNormals:function(a){var b,c,d,e,g,f,h=new THREE.Vector3,i=new THREE.Vector3;d=0;for(e=this.faces.length;d<e;d++){g=this.faces[d];if(a&&g.vertexNormals.length){h.set(0,0,0);b=0;for(c=g.vertexNormals.length;b<c;b++)h.addSelf(g.vertexNormals[b]);h.divideScalar(3)}else{b=this.vertices[g.a];c=this.vertices[g.b];f=this.vertices[g.c];h.sub(f.position,c.position);i.sub(b.position,c.position);h.crossSelf(i)}h.isZero()||
h.normalize();g.normal.copy(h)}},computeVertexNormals:function(){var a,b,c,d;if(this.__tmpVertices==void 0){d=this.__tmpVertices=Array(this.vertices.length);a=0;for(b=this.vertices.length;a<b;a++)d[a]=new THREE.Vector3;a=0;for(b=this.faces.length;a<b;a++){c=this.faces[a];if(c instanceof THREE.Face3)c.vertexNormals=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3];else if(c instanceof THREE.Face4)c.vertexNormals=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3,new THREE.Vector3]}}else{d=
this.__tmpVertices;a=0;for(b=this.vertices.length;a<b;a++)d[a].set(0,0,0)}a=0;for(b=this.faces.length;a<b;a++){c=this.faces[a];if(c instanceof THREE.Face3){d[c.a].addSelf(c.normal);d[c.b].addSelf(c.normal);d[c.c].addSelf(c.normal)}else if(c instanceof THREE.Face4){d[c.a].addSelf(c.normal);d[c.b].addSelf(c.normal);d[c.c].addSelf(c.normal);d[c.d].addSelf(c.normal)}}a=0;for(b=this.vertices.length;a<b;a++)d[a].normalize();a=0;for(b=this.faces.length;a<b;a++){c=this.faces[a];if(c instanceof THREE.Face3){c.vertexNormals[0].copy(d[c.a]);
c.vertexNormals[1].copy(d[c.b]);c.vertexNormals[2].copy(d[c.c])}else if(c instanceof THREE.Face4){c.vertexNormals[0].copy(d[c.a]);c.vertexNormals[1].copy(d[c.b]);c.vertexNormals[2].copy(d[c.c]);c.vertexNormals[3].copy(d[c.d])}}},computeTangents:function(){function a(a,b,c,d,e,g,Q){h=a.vertices[b].position;i=a.vertices[c].position;j=a.vertices[d].position;m=f[e];n=f[g];l=f[Q];o=i.x-h.x;k=j.x-h.x;s=i.y-h.y;t=j.y-h.y;v=i.z-h.z;y=j.z-h.z;B=n.u-m.u;w=l.u-m.u;z=n.v-m.v;q=l.v-m.v;E=1/(B*q-w*z);J.set((q*
o-z*k)*E,(q*s-z*t)*E,(q*v-z*y)*E);S.set((B*k-w*o)*E,(B*t-w*s)*E,(B*y-w*v)*E);u[b].addSelf(J);u[c].addSelf(J);u[d].addSelf(J);p[b].addSelf(S);p[c].addSelf(S);p[d].addSelf(S)}var b,c,d,e,g,f,h,i,j,m,n,l,o,k,s,t,v,y,B,w,z,q,E,r,u=[],p=[],J=new THREE.Vector3,S=new THREE.Vector3,N=new THREE.Vector3,F=new THREE.Vector3,L=new THREE.Vector3;b=0;for(c=this.vertices.length;b<c;b++){u[b]=new THREE.Vector3;p[b]=new THREE.Vector3}b=0;for(c=this.faces.length;b<c;b++){g=this.faces[b];f=this.faceVertexUvs[0][b];
if(g instanceof THREE.Face3)a(this,g.a,g.b,g.c,0,1,2);else if(g instanceof THREE.Face4){a(this,g.a,g.b,g.c,0,1,2);a(this,g.a,g.b,g.d,0,1,3)}}var Q=["a","b","c","d"];b=0;for(c=this.faces.length;b<c;b++){g=this.faces[b];for(d=0;d<g.vertexNormals.length;d++){L.copy(g.vertexNormals[d]);e=g[Q[d]];r=u[e];N.copy(r);N.subSelf(L.multiplyScalar(L.dot(r))).normalize();F.cross(g.vertexNormals[d],r);e=F.dot(p[e]);e=e<0?-1:1;g.vertexTangents[d]=new THREE.Vector4(N.x,N.y,N.z,e)}}this.hasTangents=true},computeBoundingBox:function(){var a;
if(this.vertices.length>0){this.boundingBox={x:[this.vertices[0].position.x,this.vertices[0].position.x],y:[this.vertices[0].position.y,this.vertices[0].position.y],z:[this.vertices[0].position.z,this.vertices[0].position.z]};for(var b=1,c=this.vertices.length;b<c;b++){a=this.vertices[b];if(a.position.x<this.boundingBox.x[0])this.boundingBox.x[0]=a.position.x;else if(a.position.x>this.boundingBox.x[1])this.boundingBox.x[1]=a.position.x;if(a.position.y<this.boundingBox.y[0])this.boundingBox.y[0]=a.position.y;
else if(a.position.y>this.boundingBox.y[1])this.boundingBox.y[1]=a.position.y;if(a.position.z<this.boundingBox.z[0])this.boundingBox.z[0]=a.position.z;else if(a.position.z>this.boundingBox.z[1])this.boundingBox.z[1]=a.position.z}}},computeBoundingSphere:function(){for(var a=0,b=0,c=this.vertices.length;b<c;b++)a=Math.max(a,this.vertices[b].position.length());this.boundingSphere={radius:a}},computeEdgeFaces:function(){function a(a,b){return Math.min(a,b)+"_"+Math.max(a,b)}function b(a,b,c){if(a[b]===
void 0){a[b]={set:{},array:[]};a[b].set[c]=1;a[b].array.push(c)}else if(a[b].set[c]===void 0){a[b].set[c]=1;a[b].array.push(c)}}var c,d,e,g,f,h={};c=0;for(d=this.faces.length;c<d;c++){f=this.faces[c];if(f instanceof THREE.Face3){e=a(f.a,f.b);b(h,e,c);e=a(f.b,f.c);b(h,e,c);e=a(f.a,f.c);b(h,e,c)}else if(f instanceof THREE.Face4){e=a(f.b,f.d);b(h,e,c);e=a(f.a,f.b);b(h,e,c);e=a(f.a,f.d);b(h,e,c);e=a(f.b,f.c);b(h,e,c);e=a(f.c,f.d);b(h,e,c)}}c=0;for(d=this.edges.length;c<d;c++){f=this.edges[c];e=f.vertexIndices[0];
g=f.vertexIndices[1];f.faceIndices=h[a(e,g)].array;for(e=0;e<f.faceIndices.length;e++){g=f.faceIndices[e];f.faces.push(this.faces[g])}}}};THREE.GeometryIdCounter=0;THREE.Camera=function(a,b,c,d,e){THREE.Object3D.call(this);this.fov=a||50;this.aspect=b||1;this.near=c||0.1;this.far=d||2E3;this.target=e||new THREE.Object3D;this.useTarget=true;this.matrixWorldInverse=new THREE.Matrix4;this.projectionMatrix=null;this.updateProjectionMatrix()};THREE.Camera.prototype=new THREE.Object3D;
THREE.Camera.prototype.constructor=THREE.Camera;THREE.Camera.prototype.supr=THREE.Object3D.prototype;THREE.Camera.prototype.translate=function(a,b){this.matrix.rotateAxis(b);this.position.addSelf(b.multiplyScalar(a));this.target.position.addSelf(b.multiplyScalar(a))};THREE.Camera.prototype.updateProjectionMatrix=function(){this.projectionMatrix=THREE.Matrix4.makePerspective(this.fov,this.aspect,this.near,this.far)};
THREE.Camera.prototype.update=function(a,b,c){if(this.useTarget){this.matrix.lookAt(this.position,this.target.position,this.up);this.matrix.setPosition(this.position);a?this.matrixWorld.multiply(a,this.matrix):this.matrixWorld.copy(this.matrix);THREE.Matrix4.makeInvert(this.matrixWorld,this.matrixWorldInverse);b=true}else{this.matrixAutoUpdate&&this.updateMatrix();if(b||this.matrixWorldNeedsUpdate){a?this.matrixWorld.multiply(a,this.matrix):this.matrixWorld.copy(this.matrix);this.matrixWorldNeedsUpdate=
false;b=true;THREE.Matrix4.makeInvert(this.matrixWorld,this.matrixWorldInverse)}}for(a=0;a<this.children.length;a++)this.children[a].update(this.matrixWorld,b,c)};THREE.Light=function(a){THREE.Object3D.call(this);this.color=new THREE.Color(a)};THREE.Light.prototype=new THREE.Object3D;THREE.Light.prototype.constructor=THREE.Light;THREE.Light.prototype.supr=THREE.Object3D.prototype;
THREE.Material=function(a){this.id=THREE.MaterialCounter.value++;a=a||{};this.opacity=a.opacity!==void 0?a.opacity:1;this.transparent=a.transparent!==void 0?a.transparent:false;this.blending=a.blending!==void 0?a.blending:THREE.NormalBlending;this.depthTest=a.depthTest!==void 0?a.depthTest:true};THREE.NoShading=0;THREE.FlatShading=1;THREE.SmoothShading=2;THREE.NoColors=0;THREE.FaceColors=1;THREE.VertexColors=2;THREE.NormalBlending=0;THREE.AdditiveBlending=1;THREE.SubtractiveBlending=2;
THREE.MultiplyBlending=3;THREE.AdditiveAlphaBlending=4;THREE.MaterialCounter={value:0};
THREE.MeshBasicMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.color=a.color!==void 0?new THREE.Color(a.color):new THREE.Color(16777215);this.map=a.map!==void 0?a.map:null;this.lightMap=a.lightMap!==void 0?a.lightMap:null;this.envMap=a.envMap!==void 0?a.envMap:null;this.combine=a.combine!==void 0?a.combine:THREE.MultiplyOperation;this.reflectivity=a.reflectivity!==void 0?a.reflectivity:1;this.refractionRatio=a.refractionRatio!==void 0?a.refractionRatio:0.98;this.shading=a.shading!==
void 0?a.shading:THREE.SmoothShading;this.wireframe=a.wireframe!==void 0?a.wireframe:false;this.wireframeLinewidth=a.wireframeLinewidth!==void 0?a.wireframeLinewidth:1;this.wireframeLinecap=a.wireframeLinecap!==void 0?a.wireframeLinecap:"round";this.wireframeLinejoin=a.wireframeLinejoin!==void 0?a.wireframeLinejoin:"round";this.vertexColors=a.vertexColors!==void 0?a.vertexColors:false;this.skinning=a.skinning!==void 0?a.skinning:false;this.morphTargets=a.morphTargets!==void 0?a.morphTargets:false};
THREE.MeshBasicMaterial.prototype=new THREE.Material;THREE.MeshBasicMaterial.prototype.constructor=THREE.MeshBasicMaterial;THREE.MeshFaceMaterial=function(){};THREE.Particle=function(a){THREE.Object3D.call(this);this.materials=a instanceof Array?a:[a]};THREE.Particle.prototype=new THREE.Object3D;THREE.Particle.prototype.constructor=THREE.Particle;THREE.Line=function(a,b,c){THREE.Object3D.call(this);this.geometry=a;this.materials=b instanceof Array?b:[b];this.type=c!=void 0?c:THREE.LineStrip};
THREE.LineStrip=0;THREE.LinePieces=1;THREE.Line.prototype=new THREE.Object3D;THREE.Line.prototype.constructor=THREE.Line;
THREE.Mesh=function(a,b){THREE.Object3D.call(this);this.geometry=a;this.materials=b&&b.length?b:[b];this.overdraw=this.doubleSided=this.flipSided=false;if(this.geometry){this.geometry.boundingSphere||this.geometry.computeBoundingSphere();this.boundRadius=a.boundingSphere.radius;if(this.geometry.morphTargets.length){this.morphTargetBase=-1;this.morphTargetForcedOrder=[];this.morphTargetInfluences=[];this.morphTargetDictionary={};for(var c=0;c<this.geometry.morphTargets.length;c++){this.morphTargetInfluences.push(0);
this.morphTargetDictionary[this.geometry.morphTargets[c].name]=c}}}};THREE.Mesh.prototype=new THREE.Object3D;THREE.Mesh.prototype.constructor=THREE.Mesh;THREE.Mesh.prototype.supr=THREE.Object3D.prototype;THREE.Mesh.prototype.getMorphTargetIndexByName=function(a){if(this.morphTargetDictionary[a]!==void 0)return this.morphTargetDictionary[a];console.log("THREE.Mesh.getMorphTargetIndexByName: morph target "+a+" does not exist. Returning 0.");return 0};
THREE.Bone=function(a){THREE.Object3D.call(this);this.skin=a;this.skinMatrix=new THREE.Matrix4;this.hasNoneBoneChildren=false};THREE.Bone.prototype=new THREE.Object3D;THREE.Bone.prototype.constructor=THREE.Bone;THREE.Bone.prototype.supr=THREE.Object3D.prototype;
THREE.Bone.prototype.update=function(a,b,c){this.matrixAutoUpdate&&(b=b|this.updateMatrix());if(b||this.matrixWorldNeedsUpdate){a?this.skinMatrix.multiply(a,this.matrix):this.skinMatrix.copy(this.matrix);this.matrixWorldNeedsUpdate=false;b=true}var d,e=this.children.length;if(this.hasNoneBoneChildren){this.matrixWorld.multiply(this.skin.matrixWorld,this.skinMatrix);for(d=0;d<e;d++){a=this.children[d];a instanceof THREE.Bone?a.update(this.skinMatrix,b,c):a.update(this.matrixWorld,true,c)}}else for(d=
0;d<e;d++)this.children[d].update(this.skinMatrix,b,c)};THREE.Bone.prototype.addChild=function(a){if(this.children.indexOf(a)===-1){a.parent!==void 0&&a.parent.removeChild(a);a.parent=this;this.children.push(a);if(!(a instanceof THREE.Bone))this.hasNoneBoneChildren=true}};
THREE.Sound=function(a,b,c,d){THREE.Object3D.call(this);this.isPlaying=this.isAddedToDOM=this.isLoaded=false;this.duration=-1;this.radius=b!==void 0?Math.abs(b):100;this.volume=Math.min(1,Math.max(0,c!==void 0?c:1));this.domElement=document.createElement("audio");this.domElement.volume=0;this.domElement.pan=0;this.domElement.loop=d!==void 0?d:true;this.sources=a instanceof Array?a:[a];for(var e,c=this.sources.length,a=0;a<c;a++){b=this.sources[a];b.toLowerCase();b.indexOf(".mp3")!==-1?e="audio/mpeg":
b.indexOf(".ogg")!==-1?e="audio/ogg":b.indexOf(".wav")!==-1&&(e="audio/wav");if(this.domElement.canPlayType(e)){e=document.createElement("source");e.src=this.sources[a];this.domElement.THREESound=this;this.domElement.appendChild(e);this.domElement.addEventListener("canplay",this.onLoad,true);this.domElement.load();break}}};THREE.Sound.prototype=new THREE.Object3D;THREE.Sound.prototype.constructor=THREE.Sound;THREE.Sound.prototype.supr=THREE.Object3D.prototype;
THREE.Sound.prototype.onLoad=function(){var a=this.THREESound;if(!a.isLoaded){this.removeEventListener("canplay",this.onLoad,true);a.isLoaded=true;a.duration=this.duration;a.isPlaying&&a.play()}};THREE.Sound.prototype.addToDOM=function(a){this.isAddedToDOM=true;a.appendChild(this.domElement)};THREE.Sound.prototype.play=function(a){this.isPlaying=true;if(this.isLoaded){this.domElement.play();if(a)this.domElement.currentTime=a%this.duration}};
THREE.Sound.prototype.pause=function(){this.isPlaying=false;this.domElement.pause()};THREE.Sound.prototype.stop=function(){this.isPlaying=false;this.domElement.pause();this.domElement.currentTime=0};THREE.Sound.prototype.calculateVolumeAndPan=function(a){a=a.length();this.domElement.volume=a<=this.radius?this.volume*(1-a/this.radius):0};
THREE.Sound.prototype.update=function(a,b,c){if(this.matrixAutoUpdate){this.matrix.setPosition(this.position);b=true}if(b||this.matrixWorldNeedsUpdate){a?this.matrixWorld.multiply(a,this.matrix):this.matrixWorld.copy(this.matrix);this.matrixWorldNeedsUpdate=false;b=true}for(var d=this.children.length,a=0;a<d;a++)this.children[a].update(this.matrixWorld,b,c)};
THREE.Scene=function(){THREE.Object3D.call(this);this.matrixAutoUpdate=false;this.collisions=this.fog=null;this.objects=[];this.lights=[];this.sounds=[];this.__objectsAdded=[];this.__objectsRemoved=[]};THREE.Scene.prototype=new THREE.Object3D;THREE.Scene.prototype.constructor=THREE.Scene;THREE.Scene.prototype.supr=THREE.Object3D.prototype;THREE.Scene.prototype.addChild=function(a){this.supr.addChild.call(this,a);this.addChildRecurse(a)};
THREE.Scene.prototype.addChildRecurse=function(a){if(a instanceof THREE.Light)this.lights.indexOf(a)===-1&&this.lights.push(a);else if(a instanceof THREE.Sound)this.sounds.indexOf(a)===-1&&this.sounds.push(a);else if(!(a instanceof THREE.Camera||a instanceof THREE.Bone)&&this.objects.indexOf(a)===-1){this.objects.push(a);this.__objectsAdded.push(a)}for(var b=0;b<a.children.length;b++)this.addChildRecurse(a.children[b])};
THREE.Scene.prototype.removeChild=function(a){this.supr.removeChild.call(this,a);this.removeChildRecurse(a)};THREE.Scene.prototype.removeChildRecurse=function(a){if(a instanceof THREE.Light){var b=this.lights.indexOf(a);b!==-1&&this.lights.splice(b,1)}else if(a instanceof THREE.Sound){b=this.sounds.indexOf(a);b!==-1&&this.sounds.splice(b,1)}else if(!(a instanceof THREE.Camera)){b=this.objects.indexOf(a);if(b!==-1){this.objects.splice(b,1);this.__objectsRemoved.push(a)}}for(b=0;b<a.children.length;b++)this.removeChildRecurse(a.children[b])};
THREE.Scene.prototype.addObject=THREE.Scene.prototype.addChild;THREE.Scene.prototype.removeObject=THREE.Scene.prototype.removeChild;THREE.Scene.prototype.addLight=THREE.Scene.prototype.addChild;THREE.Scene.prototype.removeLight=THREE.Scene.prototype.removeChild;
THREE.Projector=function(){function a(){var a=i[h]=i[h]||new THREE.RenderableVertex;h++;return a}function b(a,b){return b.z-a.z}function c(a,b){var c=0,d=1,e=a.z+a.w,f=b.z+b.w,g=-a.z+a.w,h=-b.z+b.w;if(e>=0&&f>=0&&g>=0&&h>=0)return true;if(e<0&&f<0||g<0&&h<0)return false;e<0?c=Math.max(c,e/(e-f)):f<0&&(d=Math.min(d,e/(e-f)));g<0?c=Math.max(c,g/(g-h)):h<0&&(d=Math.min(d,g/(g-h)));if(d<c)return false;a.lerpSelf(b,c);b.lerpSelf(a,1-d);return true}var d,e,g=[],f,h,i=[],j,m,n=[],l,o=[],k,s,t=[],v,y,B=[],
w=new THREE.Vector4,z=new THREE.Vector4,q=new THREE.Matrix4,E=new THREE.Matrix4,r=[new THREE.Vector4,new THREE.Vector4,new THREE.Vector4,new THREE.Vector4,new THREE.Vector4,new THREE.Vector4],u=new THREE.Vector4,p=new THREE.Vector4;this.projectVector=function(a,b){q.multiply(b.projectionMatrix,b.matrixWorldInverse);q.multiplyVector3(a);return a};this.unprojectVector=function(a,b){q.multiply(b.matrixWorld,THREE.Matrix4.makeInvert(b.projectionMatrix));q.multiplyVector3(a);return a};this.projectObjects=
function(a,c,f){var c=[],h,i,k;e=0;i=a.objects;a=0;for(h=i.length;a<h;a++){k=i[a];var l;if(!(l=!k.visible))if(l=k instanceof THREE.Mesh){a:{l=void 0;for(var j=k.matrixWorld,m=-k.geometry.boundingSphere.radius*Math.max(k.scale.x,Math.max(k.scale.y,k.scale.z)),p=0;p<6;p++){l=r[p].x*j.n14+r[p].y*j.n24+r[p].z*j.n34+r[p].w;if(l<=m){l=false;break a}}l=true}l=!l}if(!l){l=g[e]=g[e]||new THREE.RenderableObject;e++;d=l;w.copy(k.position);q.multiplyVector3(w);d.object=k;d.z=w.z;c.push(d)}}f&&c.sort(b);return c};
this.projectScene=function(d,e,g){var F=[],L=e.near,Q=e.far,O,w,C,P,A,M,K,T,Y,x,H,G,I,U,Z,ea,ba;y=s=l=m=0;e.matrixAutoUpdate&&e.update(void 0,true);d.update(void 0,false,e);q.multiply(e.projectionMatrix,e.matrixWorldInverse);r[0].set(q.n41-q.n11,q.n42-q.n12,q.n43-q.n13,q.n44-q.n14);r[1].set(q.n41+q.n11,q.n42+q.n12,q.n43+q.n13,q.n44+q.n14);r[2].set(q.n41+q.n21,q.n42+q.n22,q.n43+q.n23,q.n44+q.n24);r[3].set(q.n41-q.n21,q.n42-q.n22,q.n43-q.n23,q.n44-q.n24);r[4].set(q.n41-q.n31,q.n42-q.n32,q.n43-q.n33,
q.n44-q.n34);r[5].set(q.n41+q.n31,q.n42+q.n32,q.n43+q.n33,q.n44+q.n34);for(O=0;O<6;O++){Y=r[O];Y.divideScalar(Math.sqrt(Y.x*Y.x+Y.y*Y.y+Y.z*Y.z))}Y=this.projectObjects(d,e,true);d=0;for(O=Y.length;d<O;d++){x=Y[d].object;if(x.visible){H=x.matrixWorld;G=x.matrixRotationWorld;I=x.materials;U=x.overdraw;h=0;if(x instanceof THREE.Mesh){Z=x.geometry;P=Z.vertices;ea=Z.faces;Z=Z.faceVertexUvs;w=0;for(C=P.length;w<C;w++){f=a();f.positionWorld.copy(P[w].position);H.multiplyVector3(f.positionWorld);f.positionScreen.copy(f.positionWorld);
q.multiplyVector4(f.positionScreen);f.positionScreen.x=f.positionScreen.x/f.positionScreen.w;f.positionScreen.y=f.positionScreen.y/f.positionScreen.w;f.visible=f.positionScreen.z>L&&f.positionScreen.z<Q}P=0;for(w=ea.length;P<w;P++){C=ea[P];if(C instanceof THREE.Face3){A=i[C.a];M=i[C.b];K=i[C.c];if(A.visible&&M.visible&&K.visible&&(x.doubleSided||x.flipSided!=(K.positionScreen.x-A.positionScreen.x)*(M.positionScreen.y-A.positionScreen.y)-(K.positionScreen.y-A.positionScreen.y)*(M.positionScreen.x-
A.positionScreen.x)<0)){T=n[m]=n[m]||new THREE.RenderableFace3;m++;j=T;j.v1.copy(A);j.v2.copy(M);j.v3.copy(K)}else continue}else if(C instanceof THREE.Face4){A=i[C.a];M=i[C.b];K=i[C.c];T=i[C.d];if(A.visible&&M.visible&&K.visible&&T.visible&&(x.doubleSided||x.flipSided!=((T.positionScreen.x-A.positionScreen.x)*(M.positionScreen.y-A.positionScreen.y)-(T.positionScreen.y-A.positionScreen.y)*(M.positionScreen.x-A.positionScreen.x)<0||(M.positionScreen.x-K.positionScreen.x)*(T.positionScreen.y-K.positionScreen.y)-
(M.positionScreen.y-K.positionScreen.y)*(T.positionScreen.x-K.positionScreen.x)<0))){ba=o[l]=o[l]||new THREE.RenderableFace4;l++;j=ba;j.v1.copy(A);j.v2.copy(M);j.v3.copy(K);j.v4.copy(T)}else continue}j.normalWorld.copy(C.normal);G.multiplyVector3(j.normalWorld);j.centroidWorld.copy(C.centroid);H.multiplyVector3(j.centroidWorld);j.centroidScreen.copy(j.centroidWorld);q.multiplyVector3(j.centroidScreen);K=C.vertexNormals;A=0;for(M=K.length;A<M;A++){T=j.vertexNormalsWorld[A];T.copy(K[A]);G.multiplyVector3(T)}A=
0;for(M=Z.length;A<M;A++)if(ba=Z[A][P]){K=0;for(T=ba.length;K<T;K++)j.uvs[A][K]=ba[K]}j.meshMaterials=I;j.faceMaterials=C.materials;j.overdraw=U;j.z=j.centroidScreen.z;F.push(j)}}else if(x instanceof THREE.Line){E.multiply(q,H);P=x.geometry.vertices;A=a();A.positionScreen.copy(P[0].position);E.multiplyVector4(A.positionScreen);w=1;for(C=P.length;w<C;w++){A=a();A.positionScreen.copy(P[w].position);E.multiplyVector4(A.positionScreen);M=i[h-2];u.copy(A.positionScreen);p.copy(M.positionScreen);if(c(u,
p)){u.multiplyScalar(1/u.w);p.multiplyScalar(1/p.w);H=t[s]=t[s]||new THREE.RenderableLine;s++;k=H;k.v1.positionScreen.copy(u);k.v2.positionScreen.copy(p);k.z=Math.max(u.z,p.z);k.materials=x.materials;F.push(k)}}}else if(x instanceof THREE.Particle){z.set(x.matrixWorld.n14,x.matrixWorld.n24,x.matrixWorld.n34,1);q.multiplyVector4(z);z.z=z.z/z.w;if(z.z>0&&z.z<1){H=B[y]=B[y]||new THREE.RenderableParticle;y++;v=H;v.x=z.x/z.w;v.y=z.y/z.w;v.z=z.z;v.rotation=x.rotation.z;v.scale.x=x.scale.x*Math.abs(v.x-
(z.x+e.projectionMatrix.n11)/(z.w+e.projectionMatrix.n14));v.scale.y=x.scale.y*Math.abs(v.y-(z.y+e.projectionMatrix.n22)/(z.w+e.projectionMatrix.n24));v.materials=x.materials;F.push(v)}}}}g&&F.sort(b);return F}};
THREE.CanvasRenderer=function(a){function b(a){if(v!=a)k.globalAlpha=v=a}function c(a){if(y!=a){switch(a){case THREE.NormalBlending:k.globalCompositeOperation="source-over";break;case THREE.AdditiveBlending:k.globalCompositeOperation="lighter";break;case THREE.SubtractiveBlending:k.globalCompositeOperation="darker"}y=a}}function d(a){if(B!=a.hex){B=a.hex;k.strokeStyle="#"+g(B.toString(16))}}function e(a){if(w!=a.hex){w=a.hex;k.fillStyle="#"+g(w.toString(16))}}function g(a){for(;a.length<6;)a="0"+
a;return a}var f=this,h=null,i=new THREE.Projector,a=a||{},j=a.canvas!==void 0?a.canvas:document.createElement("canvas"),m,n,l,o,k=j.getContext("2d"),s=new THREE.Color(0),t=0,v=1,y=0,B=null,w=null,z=null,q=null,E=null,r,u,p,J,S=new THREE.RenderableVertex,N=new THREE.RenderableVertex,F,L,Q,O,aa,C,P,A,M,K,T,Y,x=new THREE.Color(0),H=new THREE.Color(0),G=new THREE.Color(0),I=new THREE.Color(0),U=new THREE.Color(0),Z,ea,ba,ca,Ba,Ca,Da,Ea,Fa,Ga,ma=new THREE.Rectangle,fa=new THREE.Rectangle,X=new THREE.Rectangle,
za=false,da=new THREE.Color,W=new THREE.Color,na=new THREE.Color,oa=new THREE.Color,R=new THREE.Vector3,sa,ta,Aa,ga,ua,va,a=16;sa=document.createElement("canvas");sa.width=sa.height=2;ta=sa.getContext("2d");ta.fillStyle="rgba(0,0,0,1)";ta.fillRect(0,0,2,2);Aa=ta.getImageData(0,0,2,2);ga=Aa.data;ua=document.createElement("canvas");ua.width=ua.height=a;va=ua.getContext("2d");va.translate(-a/2,-a/2);va.scale(a,a);a--;this.domElement=j;this.sortElements=this.sortObjects=this.autoClear=true;this.data=
{vertices:0,faces:0};this.setSize=function(a,b){m=a;n=b;l=m/2;o=n/2;j.width=m;j.height=n;ma.set(-l,-o,l,o);v=1;y=0;E=q=z=w=B=null};this.setClearColor=function(a,b){s=a;t=b};this.setClearColorHex=function(a,b){s.setHex(a);t=b};this.clear=function(){k.setTransform(1,0,0,-1,l,o);if(!fa.isEmpty()){fa.inflate(1);fa.minSelf(ma);if(s.hex==0&&t==0)k.clearRect(fa.getX(),fa.getY(),fa.getWidth(),fa.getHeight());else{c(THREE.NormalBlending);b(1);k.fillStyle="rgba("+Math.floor(s.r*255)+","+Math.floor(s.g*255)+
","+Math.floor(s.b*255)+","+t+")";k.fillRect(fa.getX(),fa.getY(),fa.getWidth(),fa.getHeight())}fa.empty()}};this.render=function(a,g){function j(a){var b,c,d,e=a.lights;W.setRGB(0,0,0);na.setRGB(0,0,0);oa.setRGB(0,0,0);a=0;for(b=e.length;a<b;a++){c=e[a];d=c.color;if(c instanceof THREE.AmbientLight){W.r=W.r+d.r;W.g=W.g+d.g;W.b=W.b+d.b}else if(c instanceof THREE.DirectionalLight){na.r=na.r+d.r;na.g=na.g+d.g;na.b=na.b+d.b}else if(c instanceof THREE.PointLight){oa.r=oa.r+d.r;oa.g=oa.g+d.g;oa.b=oa.b+d.b}}}
function m(a,b,c,d){var e,f,g,h,k=a.lights,a=0;for(e=k.length;a<e;a++){f=k[a];g=f.color;if(f instanceof THREE.DirectionalLight){h=c.dot(f.position);if(!(h<=0)){h=h*f.intensity;d.r=d.r+g.r*h;d.g=d.g+g.g*h;d.b=d.b+g.b*h}}else if(f instanceof THREE.PointLight){h=c.dot(R.sub(f.position,b).normalize());if(!(h<=0)){h=h*(f.distance==0?1:1-Math.min(b.distanceTo(f.position)/f.distance,1));if(h!=0){h=h*f.intensity;d.r=d.r+g.r*h;d.g=d.g+g.g*h;d.b=d.b+g.b*h}}}}}function n(a,f,g){b(g.opacity);c(g.blending);var h,
i,m,j,p,r;if(g instanceof THREE.ParticleBasicMaterial){if(g.map){j=g.map.image;p=j.width>>1;r=j.height>>1;g=f.scale.x*l;m=f.scale.y*o;h=g*p;i=m*r;X.set(a.x-h,a.y-i,a.x+h,a.y+i);if(ma.instersects(X)){k.save();k.translate(a.x,a.y);k.rotate(-f.rotation);k.scale(g,-m);k.translate(-p,-r);k.drawImage(j,0,0);k.restore()}}}else if(g instanceof THREE.ParticleCanvasMaterial){h=f.scale.x*l;i=f.scale.y*o;X.set(a.x-h,a.y-i,a.x+h,a.y+i);if(ma.instersects(X)){d(g.color);e(g.color);k.save();k.translate(a.x,a.y);
k.rotate(-f.rotation);k.scale(h,i);g.program(k);k.restore()}}}function s(a,e,f,g){b(g.opacity);c(g.blending);k.beginPath();k.moveTo(a.positionScreen.x,a.positionScreen.y);k.lineTo(e.positionScreen.x,e.positionScreen.y);k.closePath();if(g instanceof THREE.LineBasicMaterial){a=g.linewidth;if(z!=a)k.lineWidth=z=a;a=g.linecap;if(q!=a)k.lineCap=q=a;a=g.linejoin;if(E!=a)k.lineJoin=E=a;d(g.color);k.stroke();X.inflate(g.linewidth*2)}}function t(a,d,e,h,k,i,l,j,p){f.data.vertices=f.data.vertices+3;f.data.faces++;
b(j.opacity);c(j.blending);F=a.positionScreen.x;L=a.positionScreen.y;Q=d.positionScreen.x;O=d.positionScreen.y;aa=e.positionScreen.x;C=e.positionScreen.y;w(F,L,Q,O,aa,C);if(j instanceof THREE.MeshBasicMaterial)if(j.map){if(j.map.mapping instanceof THREE.UVMapping){ca=l.uvs[0];ia(F,L,Q,O,aa,C,j.map.image,ca[h].u,ca[h].v,ca[k].u,ca[k].v,ca[i].u,ca[i].v)}}else if(j.envMap){if(j.envMap.mapping instanceof THREE.SphericalReflectionMapping){a=g.matrixWorldInverse;R.copy(l.vertexNormalsWorld[0]);Ba=(R.x*
a.n11+R.y*a.n12+R.z*a.n13)*0.5+0.5;Ca=-(R.x*a.n21+R.y*a.n22+R.z*a.n23)*0.5+0.5;R.copy(l.vertexNormalsWorld[1]);Da=(R.x*a.n11+R.y*a.n12+R.z*a.n13)*0.5+0.5;Ea=-(R.x*a.n21+R.y*a.n22+R.z*a.n23)*0.5+0.5;R.copy(l.vertexNormalsWorld[2]);Fa=(R.x*a.n11+R.y*a.n12+R.z*a.n13)*0.5+0.5;Ga=-(R.x*a.n21+R.y*a.n22+R.z*a.n23)*0.5+0.5;ia(F,L,Q,O,aa,C,j.envMap.image,Ba,Ca,Da,Ea,Fa,Ga)}}else j.wireframe?y(j.color,j.wireframeLinewidth,j.wireframeLinecap,j.wireframeLinejoin):ja(j.color);else if(j instanceof THREE.MeshLambertMaterial){if(j.map&&
!j.wireframe){if(j.map.mapping instanceof THREE.UVMapping){ca=l.uvs[0];ia(F,L,Q,O,aa,C,j.map.image,ca[h].u,ca[h].v,ca[k].u,ca[k].v,ca[i].u,ca[i].v)}c(THREE.SubtractiveBlending)}if(za)if(!j.wireframe&&j.shading==THREE.SmoothShading&&l.vertexNormalsWorld.length==3){H.r=G.r=I.r=W.r;H.g=G.g=I.g=W.g;H.b=G.b=I.b=W.b;m(p,l.v1.positionWorld,l.vertexNormalsWorld[0],H);m(p,l.v2.positionWorld,l.vertexNormalsWorld[1],G);m(p,l.v3.positionWorld,l.vertexNormalsWorld[2],I);U.r=(G.r+I.r)*0.5;U.g=(G.g+I.g)*0.5;U.b=
(G.b+I.b)*0.5;ba=wa(H,G,I,U);ia(F,L,Q,O,aa,C,ba,0,0,1,0,0,1)}else{da.r=W.r;da.g=W.g;da.b=W.b;m(p,l.centroidWorld,l.normalWorld,da);x.r=Math.max(0,Math.min(j.color.r*da.r,1));x.g=Math.max(0,Math.min(j.color.g*da.g,1));x.b=Math.max(0,Math.min(j.color.b*da.b,1));x.updateHex();j.wireframe?y(x,j.wireframeLinewidth,j.wireframeLinecap,j.wireframeLinejoin):ja(x)}else j.wireframe?y(j.color,j.wireframeLinewidth,j.wireframeLinecap,j.wireframeLinejoin):ja(j.color)}else if(j instanceof THREE.MeshDepthMaterial){Z=
g.near;ea=g.far;H.r=H.g=H.b=1-pa(a.positionScreen.z,Z,ea);G.r=G.g=G.b=1-pa(d.positionScreen.z,Z,ea);I.r=I.g=I.b=1-pa(e.positionScreen.z,Z,ea);U.r=(G.r+I.r)*0.5;U.g=(G.g+I.g)*0.5;U.b=(G.b+I.b)*0.5;ba=wa(H,G,I,U);ia(F,L,Q,O,aa,C,ba,0,0,1,0,0,1)}else if(j instanceof THREE.MeshNormalMaterial){x.r=qa(l.normalWorld.x);x.g=qa(l.normalWorld.y);x.b=qa(l.normalWorld.z);x.updateHex();j.wireframe?y(x,j.wireframeLinewidth,j.wireframeLinecap,j.wireframeLinejoin):ja(x)}}function v(a,d,e,h,j,l,k,i,p){f.data.vertices=
f.data.vertices+4;f.data.faces++;b(i.opacity);c(i.blending);if(i.map||i.envMap){t(a,d,h,0,1,3,k,i,p);t(j,e,l,1,2,3,k,i,p)}else{F=a.positionScreen.x;L=a.positionScreen.y;Q=d.positionScreen.x;O=d.positionScreen.y;aa=e.positionScreen.x;C=e.positionScreen.y;P=h.positionScreen.x;A=h.positionScreen.y;M=j.positionScreen.x;K=j.positionScreen.y;T=l.positionScreen.x;Y=l.positionScreen.y;if(i instanceof THREE.MeshBasicMaterial){B(F,L,Q,O,aa,C,P,A);i.wireframe?y(i.color,i.wireframeLinewidth,i.wireframeLinecap,
i.wireframeLinejoin):ja(i.color)}else if(i instanceof THREE.MeshLambertMaterial)if(za)if(!i.wireframe&&i.shading==THREE.SmoothShading&&k.vertexNormalsWorld.length==4){H.r=G.r=I.r=U.r=W.r;H.g=G.g=I.g=U.g=W.g;H.b=G.b=I.b=U.b=W.b;m(p,k.v1.positionWorld,k.vertexNormalsWorld[0],H);m(p,k.v2.positionWorld,k.vertexNormalsWorld[1],G);m(p,k.v4.positionWorld,k.vertexNormalsWorld[3],I);m(p,k.v3.positionWorld,k.vertexNormalsWorld[2],U);ba=wa(H,G,I,U);w(F,L,Q,O,P,A);ia(F,L,Q,O,P,A,ba,0,0,1,0,0,1);w(M,K,aa,C,T,
Y);ia(M,K,aa,C,T,Y,ba,1,0,1,1,0,1)}else{da.r=W.r;da.g=W.g;da.b=W.b;m(p,k.centroidWorld,k.normalWorld,da);x.r=Math.max(0,Math.min(i.color.r*da.r,1));x.g=Math.max(0,Math.min(i.color.g*da.g,1));x.b=Math.max(0,Math.min(i.color.b*da.b,1));x.updateHex();B(F,L,Q,O,aa,C,P,A);i.wireframe?y(x,i.wireframeLinewidth,i.wireframeLinecap,i.wireframeLinejoin):ja(x)}else{B(F,L,Q,O,aa,C,P,A);i.wireframe?y(i.color,i.wireframeLinewidth,i.wireframeLinecap,i.wireframeLinejoin):ja(i.color)}else if(i instanceof THREE.MeshNormalMaterial){x.r=
qa(k.normalWorld.x);x.g=qa(k.normalWorld.y);x.b=qa(k.normalWorld.z);x.updateHex();B(F,L,Q,O,aa,C,P,A);i.wireframe?y(x,i.wireframeLinewidth,i.wireframeLinecap,i.wireframeLinejoin):ja(x)}else if(i instanceof THREE.MeshDepthMaterial){Z=g.near;ea=g.far;H.r=H.g=H.b=1-pa(a.positionScreen.z,Z,ea);G.r=G.g=G.b=1-pa(d.positionScreen.z,Z,ea);I.r=I.g=I.b=1-pa(h.positionScreen.z,Z,ea);U.r=U.g=U.b=1-pa(e.positionScreen.z,Z,ea);ba=wa(H,G,I,U);w(F,L,Q,O,P,A);ia(F,L,Q,O,P,A,ba,0,0,1,0,0,1);w(M,K,aa,C,T,Y);ia(M,K,
aa,C,T,Y,ba,1,0,1,1,0,1)}}}function w(a,b,c,d,e,f){k.beginPath();k.moveTo(a,b);k.lineTo(c,d);k.lineTo(e,f);k.lineTo(a,b);k.closePath()}function B(a,b,c,d,e,f,g,h){k.beginPath();k.moveTo(a,b);k.lineTo(c,d);k.lineTo(e,f);k.lineTo(g,h);k.lineTo(a,b);k.closePath()}function y(a,b,c,e){if(z!=b)k.lineWidth=z=b;if(q!=c)k.lineCap=q=c;if(E!=e)k.lineJoin=E=e;d(a);k.stroke();X.inflate(b*2)}function ja(a){e(a);k.fill()}function ia(a,b,c,d,e,f,g,h,i,j,l,p,m){var r,n;r=g.width-1;n=g.height-1;h=h*r;i=i*n;c=c-a;d=
d-b;e=e-a;f=f-b;j=j*r-h;l=l*n-i;p=p*r-h;m=m*n-i;r=j*m-p*l;if(r!=0){n=1/r;r=(m*c-l*e)*n;l=(m*d-l*f)*n;c=(j*e-p*c)*n;d=(j*f-p*d)*n;a=a-r*h-c*i;b=b-l*h-d*i;k.save();k.transform(r,l,c,d,a,b);k.clip();k.drawImage(g,0,0);k.restore()}}function wa(a,b,c,d){var e=~~(a.r*255),f=~~(a.g*255),a=~~(a.b*255),g=~~(b.r*255),h=~~(b.g*255),b=~~(b.b*255),i=~~(c.r*255),j=~~(c.g*255),c=~~(c.b*255),k=~~(d.r*255),l=~~(d.g*255),d=~~(d.b*255);ga[0]=e<0?0:e>255?255:e;ga[1]=f<0?0:f>255?255:f;ga[2]=a<0?0:a>255?255:a;ga[4]=g<
0?0:g>255?255:g;ga[5]=h<0?0:h>255?255:h;ga[6]=b<0?0:b>255?255:b;ga[8]=i<0?0:i>255?255:i;ga[9]=j<0?0:j>255?255:j;ga[10]=c<0?0:c>255?255:c;ga[12]=k<0?0:k>255?255:k;ga[13]=l<0?0:l>255?255:l;ga[14]=d<0?0:d>255?255:d;ta.putImageData(Aa,0,0);va.drawImage(sa,0,0);return ua}function pa(a,b,c){a=(a-b)/(c-b);return a*a*(3-2*a)}function qa(a){a=(a+1)*0.5;return a<0?0:a>1?1:a}function ka(a,b){var c=b.x-a.x,d=b.y-a.y,e=1/Math.sqrt(c*c+d*d),c=c*e,d=d*e;b.x=b.x+c;b.y=b.y+d;a.x=a.x-c;a.y=a.y-d}var xa,Ha,D,ha,la,
ra,ya,V;this.autoClear?this.clear():k.setTransform(1,0,0,-1,l,o);f.data.vertices=0;f.data.faces=0;h=i.projectScene(a,g,this.sortElements);(za=a.lights.length>0)&&j(a);xa=0;for(Ha=h.length;xa<Ha;xa++){D=h[xa];X.empty();if(D instanceof THREE.RenderableParticle){r=D;r.x=r.x*l;r.y=r.y*o;ha=0;for(la=D.materials.length;ha<la;){V=D.materials[ha++];V.opacity!=0&&n(r,D,V,a)}}else if(D instanceof THREE.RenderableLine){r=D.v1;u=D.v2;r.positionScreen.x=r.positionScreen.x*l;r.positionScreen.y=r.positionScreen.y*
o;u.positionScreen.x=u.positionScreen.x*l;u.positionScreen.y=u.positionScreen.y*o;X.addPoint(r.positionScreen.x,r.positionScreen.y);X.addPoint(u.positionScreen.x,u.positionScreen.y);if(ma.instersects(X)){ha=0;for(la=D.materials.length;ha<la;){V=D.materials[ha++];V.opacity!=0&&s(r,u,D,V,a)}}}else if(D instanceof THREE.RenderableFace3){r=D.v1;u=D.v2;p=D.v3;r.positionScreen.x=r.positionScreen.x*l;r.positionScreen.y=r.positionScreen.y*o;u.positionScreen.x=u.positionScreen.x*l;u.positionScreen.y=u.positionScreen.y*
o;p.positionScreen.x=p.positionScreen.x*l;p.positionScreen.y=p.positionScreen.y*o;if(D.overdraw){ka(r.positionScreen,u.positionScreen);ka(u.positionScreen,p.positionScreen);ka(p.positionScreen,r.positionScreen)}X.add3Points(r.positionScreen.x,r.positionScreen.y,u.positionScreen.x,u.positionScreen.y,p.positionScreen.x,p.positionScreen.y);if(ma.instersects(X)){ha=0;for(la=D.meshMaterials.length;ha<la;){V=D.meshMaterials[ha++];if(V instanceof THREE.MeshFaceMaterial){ra=0;for(ya=D.faceMaterials.length;ra<
ya;)(V=D.faceMaterials[ra++])&&V.opacity!=0&&t(r,u,p,0,1,2,D,V,a)}else V.opacity!=0&&t(r,u,p,0,1,2,D,V,a)}}}else if(D instanceof THREE.RenderableFace4){r=D.v1;u=D.v2;p=D.v3;J=D.v4;r.positionScreen.x=r.positionScreen.x*l;r.positionScreen.y=r.positionScreen.y*o;u.positionScreen.x=u.positionScreen.x*l;u.positionScreen.y=u.positionScreen.y*o;p.positionScreen.x=p.positionScreen.x*l;p.positionScreen.y=p.positionScreen.y*o;J.positionScreen.x=J.positionScreen.x*l;J.positionScreen.y=J.positionScreen.y*o;S.positionScreen.copy(u.positionScreen);
N.positionScreen.copy(J.positionScreen);if(D.overdraw){ka(r.positionScreen,u.positionScreen);ka(u.positionScreen,J.positionScreen);ka(J.positionScreen,r.positionScreen);ka(p.positionScreen,S.positionScreen);ka(p.positionScreen,N.positionScreen)}X.addPoint(r.positionScreen.x,r.positionScreen.y);X.addPoint(u.positionScreen.x,u.positionScreen.y);X.addPoint(p.positionScreen.x,p.positionScreen.y);X.addPoint(J.positionScreen.x,J.positionScreen.y);if(ma.instersects(X)){ha=0;for(la=D.meshMaterials.length;ha<
la;){V=D.meshMaterials[ha++];if(V instanceof THREE.MeshFaceMaterial){ra=0;for(ya=D.faceMaterials.length;ra<ya;)(V=D.faceMaterials[ra++])&&V.opacity!=0&&v(r,u,p,J,S,N,D,V,a)}else V.opacity!=0&&v(r,u,p,J,S,N,D,V,a)}}}fa.addRectangle(X)}k.setTransform(1,0,0,1,0,0)}};THREE.RenderableVertex=function(){this.positionWorld=new THREE.Vector3;this.positionScreen=new THREE.Vector4;this.visible=true};THREE.RenderableVertex.prototype.copy=function(a){this.positionWorld.copy(a.positionWorld);this.positionScreen.copy(a.positionScreen)};
THREE.RenderableFace3=function(){this.v1=new THREE.RenderableVertex;this.v2=new THREE.RenderableVertex;this.v3=new THREE.RenderableVertex;this.centroidWorld=new THREE.Vector3;this.centroidScreen=new THREE.Vector3;this.normalWorld=new THREE.Vector3;this.vertexNormalsWorld=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3];this.faceMaterials=this.meshMaterials=null;this.overdraw=false;this.uvs=[[]];this.z=null};
THREE.RenderableFace4=function(){this.v1=new THREE.RenderableVertex;this.v2=new THREE.RenderableVertex;this.v3=new THREE.RenderableVertex;this.v4=new THREE.RenderableVertex;this.centroidWorld=new THREE.Vector3;this.centroidScreen=new THREE.Vector3;this.normalWorld=new THREE.Vector3;this.vertexNormalsWorld=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3,new THREE.Vector3];this.faceMaterials=this.meshMaterials=null;this.overdraw=false;this.uvs=[[]];this.z=null};
THREE.RenderableObject=function(){this.z=this.object=null};THREE.RenderableParticle=function(){this.rotation=this.z=this.y=this.x=null;this.scale=new THREE.Vector2;this.materials=null};THREE.RenderableLine=function(){this.z=null;this.v1=new THREE.RenderableVertex;this.v2=new THREE.RenderableVertex;this.materials=null};
THREE.Plane=function(a,b,c,d){THREE.Geometry.call(this);var e,g=a/2,f=b/2,c=c||1,d=d||1,h=c+1,i=d+1,a=a/c,j=b/d;for(e=0;e<i;e++)for(b=0;b<h;b++)this.vertices.push(new THREE.Vertex(new THREE.Vector3(b*a-g,-(e*j-f),0)));for(e=0;e<d;e++)for(b=0;b<c;b++){this.faces.push(new THREE.Face4(b+h*e,b+h*(e+1),b+1+h*(e+1),b+1+h*e));this.faceVertexUvs[0].push([new THREE.UV(b/c,e/d),new THREE.UV(b/c,(e+1)/d),new THREE.UV((b+1)/c,(e+1)/d),new THREE.UV((b+1)/c,e/d)])}this.computeCentroids();this.computeFaceNormals()};
THREE.Plane.prototype=new THREE.Geometry;THREE.Plane.prototype.constructor=THREE.Plane;window.twistyjs={};
(function(){var a=window.cancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout,b=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){return window.setTimeout(a,1E3/60)}}();if(!Function.prototype.bind)Function.prototype.bind=
function(a){if(typeof this!=="function")throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice,c=b.call(arguments,1),f=this,h=function(){},i=function(){return f.apply(this instanceof h?this:a||window,c.concat(b.call(arguments)))};h.prototype=this.prototype;i.prototype=new h;return i};var c={};twistyjs.registerTwisty=function(a,b){c[a]=b};twistyjs.TwistyScene=function(){function d(a){a.preventDefault();p.addEventListener("mousemove",
e,false);p.addEventListener("mouseup",g,false);p.addEventListener("mouseout",f,false);S=a.clientX}function e(a){mouseX=a.clientX;s.cam((S-mouseX)/256);S=mouseX}function g(){p.removeEventListener("mousemove",e,false);p.removeEventListener("mouseup",g,false);p.removeEventListener("mouseout",f,false)}function f(){p.removeEventListener("mousemove",e,false);p.removeEventListener("mouseup",g,false);p.removeEventListener("mouseout",f,false)}function h(a){if(a.touches.length==1){a.preventDefault();S=a.touches[0].pageX}}
function i(a){if(a.touches.length==1){a.preventDefault();mouseX=a.touches[0].pageX;s.cam((S-mouseX)/256);S=mouseX}}function j(){q.render(z,w)}function m(a){r=a;w.position=new THREE.Vector3(2.5*Math.sin(a),2,2.5*Math.cos(a))}function n(){v=0;y=B.shift();L=$.now();for(var a=y,b=0;b<N.length;b++)N[b](a,true)}function l(){if(F!==null){a(F);F=null}}function o(){if(F===null){n();F=b(k,E)}}function k(a){a=a||$.now();a=(a-L+10)*(B.length+1)/(100+50*Math.log(B.length+1));a=Math.max(Math.min(a-v,1),0.05);v=
v+a;if(v<1)t.animateMoveCallback(t,y,v);else{t.advanceMoveCallback(t,y);for(var a=y,c=0;c<N.length;c++)N[c](a,false);y=null;B.length==0?l():n()}j();u&&u.update();F!==null&&(F=b(k,E))}var s=this,t=null,v=null,y=null,B=[],w,z,q,E,r=0,u=null;Math.TAU=Math.PI*2;var p=$("<div/>");p.css("width","100%");p.css("height","100%");p=p[0];this.getDomElement=function(){return p};this.getCanvas=function(){return E};this.getTwisty=function(){return t};this.initializeTwisty=function(a){B=[];y=null;v=0;l();$(p).empty();
z=new THREE.Scene;var b=c[a.type];if(b)t=b(s,a);else{err('Twisty type "'+a.type+'" is not recognized!');t=null}z.addObject(t._3d);q=new THREE.CanvasRenderer;E=q.domElement;p.appendChild(E);if(a.allowDragging){$(p).css("cursor","move");p.addEventListener("mousedown",d,false);p.addEventListener("touchstart",h,false);p.addEventListener("touchmove",i,false)}if(a.showFps){u=new Stats;u.domElement.style.position="absolute";u.domElement.style.top="0px";u.domElement.style.left="0px";p.appendChild(u.domElement);
$(u.domElement).click()}s.resize()};this.resize=function(){var a=Math.min($(p).width(),$(p).height());w=new THREE.Camera(30,1,0,1E3);m(0);w.target.position=new THREE.Vector3(0,-0.075,0);q.setSize(a,a);j()};this.keydown=function(a){var b=a.keyCode;t.keydownCallback(t,a);switch(b){case 37:r=r+Math.TAU/48;m(r);j();a.preventDefault();break;case 39:r=r+-Math.TAU/48;m(r);j();a.preventDefault()}};var J=0,S=0;this.cam=function(a){J=J+a;m(J);j()};var N=[];this.addMoveListener=function(a){N.push(a)};this.removeMoveListener=
function(a){a=N.indexOf(a);delete N[a]};this.animateMoves=function(a){B=B.concat(a);B.length>0&&o()};this.addMoves=function(a){B=B.concat(a);B.length>0&&o();Math.min(0.15+0.1*B.length,1)};this.applyMoves=function(a){for(B=a;B.length>0;){n();t.advanceMoveCallback(t,y)}j()};var F=null,L}})();
(function(){twistyjs.registerTwisty("plane",function(a,b){var c=new THREE.MeshLambertMaterial({color:16746496}),c=new THREE.Mesh(new THREE.PlaneGeometry(1,1),c);c.rotation.x=Math.TAU/4;c.doubleSided=true;return{type:b,_3d:c,twisty:twisty,updateTwistyCallback:function(a){a._3d.rotation.z=a._3d.rotation.z+0.01}}});twistyjs.registerTwisty("cube",function(a,b){function c(a,b,c){var d=new THREE.Matrix4;d.set(a.x,b.x,c.x,0,a.y,b.y,c.y,0,a.z,b.z,c.z,0,0,0,0,1);return d}function d(a,b){var c=null;if(b<0){c=
new THREE.Matrix4;c=THREE.Matrix4.makeInvert(a,c)}else c=a.clone();for(var d=new THREE.Matrix4,e=0;e<Math.abs(b);e++)d.multiplySelf(c);return d}function e(a,b){for(var c=a.flatten(),d=b.flatten(),e=0;e<c.length;e++)if(c[e]!=d[e])return false;return true}var g=new THREE.Object3D,f=[],h={stickerBorder:true,stickerWidth:1.8,doubleSided:true,opacity:1,dimension:3,faceColors:[16777215,16746496,65280,16711680,255,16776960],scale:1},i;for(i in h)i in b&&(h[i]=b[i]);i=[];var j=new THREE.MeshBasicMaterial({color:0,
wireframe:true,wireframeLinewidth:2});j.opacity=h.opacity;for(var m=0;m<6;m++){var n=new THREE.MeshBasicMaterial({color:h.faceColors[m]});n.opacity=h.opacity;i.push(n)}for(var m=new THREE.Vector3(1,0,0),n=new THREE.Vector3(0,1,0),l=new THREE.Vector3(0,0,1),o=new THREE.Vector3(-1,0,0),k=new THREE.Vector3(0,-1,0),s=new THREE.Vector3(0,0,-1),t=["U","L","F","R","B","D"],v={U:c(l,n,o),L:c(m,l,k),F:c(k,m,l),R:c(m,s,n),B:c(n,o,l),D:c(s,n,m)},y={U:n,L:o,F:l,R:m,B:s,D:k},B={U:k,L:m,F:s,R:o,B:l,D:n},n=[c(m,
s,n),c(l,n,o),c(m,n,l),c(s,n,m),c(o,n,s),c(m,l,k)],m=0;m<6;m++){l=[];f.push(l);for(o=0;o<h.dimension;o++)for(k=0;k<h.dimension;k++){var s=new THREE.Object3D,w=[i[m]];h.stickerBorder&&w.push(j);w=new THREE.Mesh(new THREE.Plane(h.stickerWidth,h.stickerWidth),w);w.doubleSided=h.doubleSided;s.addChild(w);w=new THREE.Matrix4;w.setTranslation(o*2-h.dimension+1,-(k*2-h.dimension+1),h.dimension);var z=new THREE.Matrix4;z.copy(n[m]);z.multiplySelf(w);s.matrix.copy(z);s.matrixAutoUpdate=false;s.update();l.push([z,
s]);g.addChild(s)}}i=h.scale*0.5/h.dimension;g.scale=new THREE.Vector3(i,i,i);i=h.dimension;var q={73:[1,1,"R",1],75:[1,1,"R",-1],87:[1,1,"B",1],79:[1,1,"B",-1],83:[1,1,"D",1],76:[1,1,"D",-1],68:[1,1,"L",1],69:[1,1,"L",-1],74:[1,1,"U",1],70:[1,1,"U",-1],72:[1,1,"F",1],71:[1,1,"F",-1],186:[1,i,"U",1],59:[1,i,"U",1],65:[1,i,"U",-1],85:[1,2,"R",1],82:[1,2,"L",-1],77:[1,2,"R",-1],86:[1,2,"L",1],84:[1,i,"L",-1],89:[1,i,"R",1],78:[1,i,"R",-1],66:[1,i,"L",1],190:[2,2,"R",1],80:[1,i,"F",1],81:[1,i,"F",-1]},
E=[];for(i=0;i<f.length;i++){j=f[i];n=[];E.push(n);for(m=0;m<j.length;m++)n.push(f[i][m][0].clone())}return{type:b,options:h,_3d:g,cubePieces:f,animateMoveCallback:function(a,b,c){var d=new THREE.Matrix4;d.setRotationAxis(B[b[2]],c*b[3]*Math.TAU/4);for(var c=a.cubePieces,e=0;e<c.length;e++)for(var f=c[e],g=0;g<f.length;g++){var h=c[e][g],i=b[0],j=b[1];j<0&&(j=a.options.dimension+1+j);var k=h[1].matrix.n14*y[b[2]].x+h[1].matrix.n24*y[b[2]].y+h[1].matrix.n34*y[b[2]].z;if(k<a.options.dimension-2*i+2.5&&
k>a.options.dimension-2*j-0.5){i=d.clone();i.multiplySelf(h[0]);h[1].matrix.copy(i);h[1].update()}}},advanceMoveCallback:function(a,b){for(var c=d(v[b[2]],b[3]),e=a.cubePieces,f=0;f<e.length;f++)for(var g=e[f],h=0;h<g.length;h++){var i=e[f][h],j=i[1].matrix.n14*y[b[2]].x+i[1].matrix.n24*y[b[2]].y+i[1].matrix.n34*y[b[2]].z;if(j<a.options.dimension-2*b[0]+2.5&&j>a.options.dimension-2*b[1]-0.5){j=c.clone();j.multiplySelf(i[0]);i[1].matrix.copy(j);i[0].copy(j);i[1].update()}}},keydownCallback:function(b,
c){if(!c.altKey&&!c.ctrlKey){var d=c.keyCode;d in q&&a.addMoves([q[d]])}},isSolved:function(a){for(var b=a.cubePieces,a=a.options.dimension,c=0,f=0,g=b[c][f][0],h=new THREE.Matrix4,h=THREE.Matrix4.makeInvert(E[c][f],h),h=h.multiply(g,h),c=0;c<b.length;c++){g=b[c];for(f=0;f<g.length;f++){var i=b[c][f][0],j=Math.floor(f/a),k=f%a;if(j>0&&j<a-1&&k>0&&k<a-1){for(var k=d(v[t[c]],1),l=E[c][f].clone(),m=false,j=0;j<4;j++){var n=new THREE.Matrix4,n=o.multiply(h,l);if(e(i,n)){m=true;break}l.multiply(k,l)}if(!m)return false}else{var o=
new THREE.Matrix4,o=o.multiply(h,E[c][f]);if(!e(i,o))return false}}}return true},isInspectionLegalMove:function(a,b){return b[0]==1&&b[1]==a.options.dimension?true:false},generateScramble:function(a){for(var a=a.options.dimension,b=[],c=0;c<32;c++){var d=1+Math.floor(Math.random()*a/2),e=d+Math.floor(Math.random()*a/2),f=Math.floor(Math.random()*6),g=[-2,-1,1,2][Math.floor(Math.random()*4)];b.push([d,e,["U","L","F","R","B","D"][f],g])}return b}}});twistyjs.registerTwisty("blank",function(a,b){var c=
new THREE.Object3D;return{type:b,_3d:c,updateTwistyCallback:function(){}}})})();
